# Generated by Django 4.2.2 on 2023-06-20 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snacks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='snack',
            old_name='description',
            new_name='desc',
        ),
    ]
